//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_Employee
    {
        public int Id { get; set; }
        public string employeecode { get; set; }
        public string displayname { get; set; }
        public Nullable<int> deskcode { get; set; }
        public Nullable<int> publicationcode { get; set; }
        public string ldapint { get; set; }
        public Nullable<int> groupcode { get; set; }
        public string reportingdesk { get; set; }
        public string status { get; set; }
    }
}
