//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReporterEntities : DbContext
    {
        public ReporterEntities()
            : base("name=ReporterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DW_Employee> DW_Employee { get; set; }
        public virtual DbSet<ServiceName> ServiceNames { get; set; }
        public virtual DbSet<ServicePermission> ServicePermissions { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
        public virtual DbSet<View_VideoSummary> View_VideoSummary { get; set; }
        public virtual DbSet<VideoManager> VideoManagers { get; set; }
        public virtual DbSet<VideoSummary> VideoSummaries { get; set; }
    }
}
