//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public int DesignationId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> IsReporter { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Holiday { get; set; }
        public string NewswrapCode { get; set; }
        public string NewswrapDesk { get; set; }
        public Nullable<int> NewswrapCenter { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string BishalGroup { get; set; }
        public string Address { get; set; }
        public Nullable<int> DistrictNameId { get; set; }
        public Nullable<int> UpazillaNameId { get; set; }
        public Nullable<int> IsMohanogor { get; set; }
        public string ReportGroup { get; set; }
        public Nullable<int> ReportOrder { get; set; }
        public Nullable<int> ApprovePermission { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<bool> IsPhotoHead { get; set; }
        public string LDAPUser { get; set; }
    }
}
