//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoSummary()
        {
            this.VideoManagers = new HashSet<VideoManager>();
        }
    
        public decimal Id { get; set; }
        public string VideoName { get; set; }
        public string VideoPath { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CenterCode { get; set; }
        public Nullable<System.DateTime> VideoDate { get; set; }
        public string Description { get; set; }
        public string VideoSize { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string GoogleDriveId { get; set; }
        public string GoogleStreamingLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoManager> VideoManagers { get; set; }
    }
}
