//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoManager
    {
        public int VideoManagerId { get; set; }
        public decimal VideoSummaryId { get; set; }
        public Nullable<int> TakenByUserId { get; set; }
        public Nullable<System.DateTime> TakenByTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public string Status { get; set; }
        public string LocalCompletedFilePath { get; set; }
        public string YoutubeId { get; set; }
    
        public virtual VideoSummary VideoSummary { get; set; }
    }
}
