//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_VideoSummary
    {
        public decimal Id { get; set; }
        public string VideoName { get; set; }
        public string VideoPath { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> VideoDate { get; set; }
        public string Description { get; set; }
        public string VideoSize { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
