//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloVideoManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User
    {
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public int DesignationId { get; set; }
        public string FullName { get; set; }
        public Nullable<int> IsReporter { get; set; }
        public string MobileNo { get; set; }
        public string NewswrapCode { get; set; }
        public string NewswrapDesk { get; set; }
        public Nullable<int> NewswrapCenter { get; set; }
        public string FullDes { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Holiday { get; set; }
    }
}
